In [3]:
import numpy as np

In [13]:
ranks = np.array([1/3., 1/3., 1/3.])
trainsition = np.asarray([[0, 1/2., 1/2.], [0, 0, 1], [0, 1, 0]])
teleport = np.asarray([[1/3., 1/3., 1/3.], [1/3., 1/3., 1/3.], [1/3., 1/3., 1/3.]])

In [14]:
P = 0.9 * trainsition + 0.1 * teleport
print P

[[ 0.03333333  0.48333333  0.48333333]
 [ 0.03333333  0.03333333  0.93333333]
 [ 0.03333333  0.93333333  0.03333333]]


In [15]:
ranks = np.dot(ranks, P)
print ranks

[ 0.03333333  0.48333333  0.48333333]


In [18]:
ranks = np.dot(ranks, P)
print ranks

[ 0.03333333  0.48333333  0.48333333]


Ответ: Page rank документов 1, 2, 3 : 0.03333333, 0.48333333, 0.48333333